"""Profile the exported TAWOS tables before any labelling code is written.

Answers the "check this first" questions from the ML implementation guide:
how sprint history is stored, how much usable data each project has, how
often acceptance criteria appear, how reliable story points are, and how
common dependencies and reopenings are. Writes a Markdown report.

Usage:
    erp-profile-tawos                       # writes ml-engine/reports/tawos-profile.md
"""

import argparse
import re
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.compute as pc

from erp import config, tawos

# Preliminary candidate filter (guide section 6.4). Final rules belong in the labelling pipeline.
EXCLUDED_TYPES = {"Epic", "Sub-task", "Technical task"}
SP_RANGE = (1, 100)
MIN_PROJECT_STORIES = 100
DEPENDENCY_LINKS = {"Blocks", "Depends", "Dependency"}
FIBONACCI = {0.5, 1, 2, 3, 5, 8, 13, 20, 21, 34, 40, 55, 89, 100}

AC_PATTERNS = {
    "mentions acceptance criteria / tests": re.compile(r"acceptance\s+(criteria|criterion|tests?)", re.I),
    "Given / When / Then": re.compile(r"\bgiven\b.{0,400}?\bwhen\b.{0,400}?\bthen\b", re.I | re.S),
    "definition of done": re.compile(r"definition\s+of\s+done", re.I),
    "checklist markup": re.compile(r"^\s*[-*#]+\s*\[[ xX]?\]", re.M),
}


def sprint_histories(change_log: pd.DataFrame) -> pd.DataFrame:
    """One row per issue: every sprint it ever belonged to (in order), and its final sprint list."""
    sprints = change_log.sort_values(["Issue_ID", "Creation_Date", "ID"])
    rows = []
    for issue_id, changes in sprints.groupby("Issue_ID", sort=False):
        ever: list[int] = []
        for value in changes["To_Value"]:
            for sprint in tawos.parse_sprint_ids(value):
                if sprint not in ever:
                    ever.append(sprint)
        final = tawos.parse_sprint_ids(changes["To_Value"].iloc[-1])
        rows.append({"Issue_ID": issue_id, "ever": ever, "final": final, "n_changes": len(changes)})
    return pd.DataFrame(rows).set_index("Issue_ID")


def pct(part, whole) -> str:
    return f"{100 * part / whole:.1f}%" if whole else "n/a"


def md_table(df: pd.DataFrame) -> str:
    header = "| " + " | ".join(map(str, df.columns)) + " |"
    rule = "|" + "|".join("---" for _ in df.columns) + "|"
    body = ["| " + " | ".join(map(str, row)) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, rule, *body])


def build_report() -> str:
    projects = tawos.load("Project", ["ID", "Project_Key", "Name", "Repository_ID"])
    repos = tawos.load("Repository", ["ID", "Name"]).rename(columns={"ID": "Repository_ID", "Name": "Repository"})
    sprints = tawos.load("Sprint")
    issues = tawos.load("Issue", [
        "ID", "Issue_Key", "Type", "Status", "Story_Point", "Project_ID", "Sprint_ID", "Title", "Estimation_Date",
        "Title_Changed_After_Estimation", "Description_Changed_After_Estimation",
        "Story_Point_Changed_After_Estimation",
    ])
    sprint_log = tawos.load("Change_Log", ["ID", "Issue_ID", "To_Value", "Creation_Date"],
                            filters=pc.field("Field") == "Sprint")
    description_log = tawos.load("Change_Log", ["Issue_ID", "Creation_Date"],
                                 filters=pc.field("Field") == "description")
    status_log = tawos.load("Change_Log", ["Issue_ID", "To_String"], filters=pc.field("Field") == "status")
    links = tawos.load("Issue_Link", ["Issue_ID", "Name"])
    link_changes = tawos.load("Change_Log", ["ID"], filters=pc.field("Field") == "Link")

    out: list[str] = ["# TAWOS data profile", ""]
    out += [
        "Generated by `erp-profile-tawos` from the Parquet export (see `_manifest.json` for the dump's SHA-256).",
        "Counts only; no issue text is reproduced here.", "",
        "## 1. Dataset size", "",
        md_table(pd.DataFrame({
            "Table": ["Repository", "Project", "Sprint", "Issue", "Issue with story points", "Change_Log (Sprint field)",
                      "Issue_Link"],
            "Rows": [f"{len(repos):,}", f"{len(projects):,}", f"{len(sprints):,}", f"{len(issues):,}",
                     f"{issues.Story_Point.notna().sum():,}", f"{len(sprint_log):,}", f"{len(links):,}"],
        })), "",
    ]

    # ---- 2. How sprint membership is stored --------------------------------------------------
    history = sprint_histories(sprint_log)
    history["n_ever"] = history["ever"].map(len)
    sprint_jira = sprints.set_index("ID")["JiraID"]
    issue_sprint = issues.set_index("ID")["Sprint_ID"].map(sprint_jira)
    multi = history[history.n_ever >= 2].join(issue_sprint.rename("sprint_id_jira"))
    first = multi.apply(lambda r: r.sprint_id_jira == r.ever[0], axis=1)
    last_added = multi.apply(lambda r: r.sprint_id_jira == r.ever[-1], axis=1)
    in_final = multi.apply(lambda r: r.sprint_id_jira in r.final, axis=1)
    no_sprint_id = multi.sprint_id_jira.isna()
    has_sprint_id = issues.Sprint_ID.notna()
    sprint_id_without_history = (has_sprint_id & ~issues.ID.isin(history.index)).sum()
    dup = sprints.merge(projects[["ID", "Repository_ID"]], left_on="Project_ID", right_on="ID")
    dup_groups = dup.groupby(["Repository_ID", "JiraID"]).size()

    out += [
        "## 2. How sprint membership is stored", "",
        f"- Issues with at least one change to the Sprint field: **{len(history):,}**; "
        f"issues that were ever in two or more sprints: **{len(multi):,}**.",
        "- Each change stores the *whole* list of sprints (e.g. `103` then `103, 106`), so the full "
        "membership history can be rebuilt from `Change_Log`.",
        f"- `Issue.Sprint_ID` is set for {has_sprint_id.sum():,} issues; "
        f"{sprint_id_without_history:,} of them have no Sprint history in `Change_Log`.",
        f"- For the {len(multi):,} multi-sprint issues, `Issue.Sprint_ID` is empty for "
        f"{pct(no_sprint_id.sum(), len(multi))}. When it is set, it is a sprint from the issue's final list "
        f"({pct(in_final.sum(), (~no_sprint_id).sum())} of those), consistent with the TAWOS description of it as "
        f"the sprint the issue was delivered in; it matches the first sprint in {pct(first.sum(), (~no_sprint_id).sum())} "
        f"and the most recently added one in {pct(last_added.sum(), (~no_sprint_id).sum())}. "
        "**It cannot be used on its own for spillover or carry-over labels (R1, R2, R5); membership must come "
        "from the `Change_Log` history.**",
        f"- `Sprint.JiraID` is not unique: {len(sprints):,} sprint rows, {sprints.JiraID.nunique():,} distinct Jira IDs, "
        f"{len(dup_groups):,} distinct (repository, Jira ID) pairs; {int((dup_groups > 1).sum()):,} pairs appear in "
        "more than one project (a sprint shared by several projects is stored once per project). "
        "Sprint IDs from `Change_Log` must be resolved per repository and project.", "",
    ]

    # ---- 3. Candidate stories per project ---------------------------------------------------
    sp = issues.Story_Point
    in_any_sprint = issues.ID.isin(history.index) | has_sprint_id
    candidate = (
        sp.between(*SP_RANGE) & ~issues.Type.isin(EXCLUDED_TYPES)
        & issues.Title.fillna("").str.strip().ne("") & in_any_sprint
    )
    cand = issues[candidate].copy()
    cand["multi_sprint"] = cand.ID.isin(multi.index)

    # A sprint is only usable for risk labels if it resolves to a Sprint row with dates in the
    # issue's own repository (Jira sprint IDs are only unique within one Jira instance).
    sprint_ok = sprints.Start_Date.notna() & sprints.End_Date.notna()
    repo_of_project = projects.set_index("ID").Repository_ID
    dated_keys = set(zip(sprints[sprint_ok].Project_ID.map(repo_of_project), sprints[sprint_ok].JiraID))
    ever = history["ever"].explode().dropna().astype(int).rename("JiraID").reset_index()
    ever["Repository_ID"] = ever.Issue_ID.map(issues.set_index("ID").Project_ID).map(repo_of_project)
    ever["dated"] = [key in dated_keys for key in zip(ever.Repository_ID, ever.JiraID)]
    dated_via_history = set(ever.loc[ever.dated, "Issue_ID"])
    dated_via_sprint_id = set(issues.ID[issues.Sprint_ID.isin(sprints.ID[sprint_ok])])
    cand["dated_sprint"] = cand.ID.isin(dated_via_history | dated_via_sprint_id)
    labelable = cand[cand.dated_sprint]

    sprints["days"] = (sprints.End_Date - sprints.Start_Date).dt.total_seconds() / 86400
    per_sprint = sprints[sprint_ok].groupby("Project_ID").agg(
        dated_sprints=("ID", "size"), median_sprint_days=("days", "median"))

    per_project = (
        issues.groupby("Project_ID").agg(issues=("ID", "size"), with_sp=("Story_Point", "count"))
        .join(cand.groupby("Project_ID").agg(candidates=("ID", "size"), dated=("dated_sprint", "sum"),
                                             multi_sprint=("multi_sprint", "sum")))
        .join(sprints.groupby("Project_ID").size().rename("sprints"))
        .fillna(0)
        .join(per_sprint)
        .join(projects.set_index("ID")[["Project_Key", "Repository_ID"]])
        .merge(repos, on="Repository_ID", how="left")
        .sort_values("dated", ascending=False)
    )
    per_project["eligible"] = np.where(per_project.dated >= MIN_PROJECT_STORIES, "yes", "")
    table = per_project.assign(
        multi_sprint_share=[pct(m, c) for m, c in zip(per_project.multi_sprint, per_project.candidates)],
        median_sprint_days=per_project.median_sprint_days.map(lambda d: "–" if pd.isna(d) else f"{d:.1f}"),
        dated_sprints=per_project.dated_sprints.fillna(0),
    )[["Project_Key", "Repository", "issues", "with_sp", "candidates", "dated", "multi_sprint_share",
       "sprints", "dated_sprints", "median_sprint_days", "eligible"]]
    table = table.rename(columns={"dated": "in dated sprint"})
    for column in ["issues", "with_sp", "candidates", "in dated sprint", "sprints", "dated_sprints"]:
        table[column] = table[column].astype(int).map("{:,}".format)
    eligible = per_project[per_project.dated >= MIN_PROJECT_STORIES]
    no_sprint_rows = per_project[(per_project.sprints == 0) & (per_project.candidates > 0)]

    out += [
        "## 3. Candidate stories per project", "",
        f"Preliminary filter: story points in {SP_RANGE[0]}–{SP_RANGE[1]}, type not in "
        f"{', '.join(sorted(EXCLUDED_TYPES))}, non-empty title, and in at least one sprint. "
        "*In dated sprint* additionally requires one of those sprints to resolve to a `Sprint` row with "
        "start and end dates in the issue's own repository; only those stories can get risk labels.", "",
        f"- Candidate stories: **{len(cand):,}** across {cand.Project_ID.nunique()} projects; "
        f"in a dated sprint: **{len(labelable):,}** ({pct(len(labelable), len(cand))}).",
        f"- Projects whose sprints are missing from the `Sprint` table entirely: "
        f"{', '.join(no_sprint_rows.Project_Key)} ({int(no_sprint_rows.candidates.sum()):,} candidates with no sprint dates).",
        f"- Projects with at least {MIN_PROJECT_STORIES} stories in dated sprints (own model possible): "
        f"**{len(eligible)}**, holding {int(eligible.dated.sum()):,} of them ({pct(eligible.dated.sum(), len(labelable))}).",
        f"- Stories in dated sprints that were in two or more sprints (carry-over signal for R5): "
        f"**{int(labelable.multi_sprint.sum()):,}** ({pct(labelable.multi_sprint.sum(), len(labelable))}).", "",
        md_table(table), "",
    ]

    # ---- 4. Story points ---------------------------------------------------------------------
    edits = description_log.merge(cand[["ID", "Estimation_Date"]], left_on="Issue_ID", right_on="ID")
    edited_ids = edits.loc[edits.Creation_Date > edits.Estimation_Date, "Issue_ID"].unique()
    edited_after = cand.ID.isin(edited_ids)
    q = cand.Story_Point.quantile([0.25, 0.5, 0.75, 0.9, 0.99])
    fib = cand.Story_Point.isin(FIBONACCI)
    all_sp = issues.Story_Point.dropna()
    out += [
        "## 4. Story points (candidates)", "",
        f"- Quartiles: 25% = {q[0.25]:g}, median = {q[0.5]:g}, 75% = {q[0.75]:g}; 90% = {q[0.9]:g}, 99% = {q[0.99]:g}.",
        f"- Values on a Fibonacci-like scale: {pct(fib.sum(), len(cand))}.",
        f"- Removed as implausible (outside {SP_RANGE[0]}–{SP_RANGE[1]}) among all pointed issues: "
        f"{(~all_sp.between(*SP_RANGE)).sum():,} of {len(all_sp):,} ({pct((~all_sp.between(*SP_RANGE)).sum(), len(all_sp))}), "
        f"of which {(all_sp == 0).sum():,} are 0.",
        f"- TAWOS flags: story points changed after estimation {pct((cand.Story_Point_Changed_After_Estimation == 1).sum(), len(cand))}, "
        f"title changed after estimation {pct((cand.Title_Changed_After_Estimation == 1).sum(), len(cand))}.",
        f"- **`Description_Changed_After_Estimation` is 0 for every pointed issue in this dump** "
        f"({(issues.Description_Changed_After_Estimation[issues.Story_Point.notna()] == 0).mean():.0%}), yet `Change_Log` records "
        f"a description edit after `Estimation_Date` for {pct(edited_after.sum(), len(cand))} of candidates. "
        "The flag cannot be used to select stories with unchanged text; use `Change_Log` instead.",
        "", "Candidates by type:", "",
        md_table(cand.Type.value_counts().rename_axis("Type").reset_index(name="Candidates")), "",
    ]

    # ---- 5. Acceptance criteria prevalence -------------------------------------------------
    text = tawos.load("Issue", ["ID", "Description"], filters=pc.field("ID").isin(cand.ID.tolist()))
    text = text.set_index("ID").Description.fillna("")
    ac_rows, any_ac = [], pd.Series(False, index=text.index)
    for name, pattern in AC_PATTERNS.items():
        hit = text.map(lambda s, p=pattern: bool(p.search(s)))
        any_ac |= hit
        ac_rows.append({"Pattern": name, "Candidates": f"{hit.sum():,}", "Share": pct(hit.sum(), len(text))})
    ac_rows.append({"Pattern": "**any of the above**", "Candidates": f"{any_ac.sum():,}", "Share": pct(any_ac.sum(), len(text))})
    ac_by_project = any_ac.groupby(cand.set_index("ID").Project_ID).mean().sort_values(ascending=False)
    top = ac_by_project.head(5).rename(index=projects.set_index("ID").Project_Key)
    out += [
        "## 5. Acceptance criteria in descriptions (candidates)", "",
        f"- Empty descriptions: {pct((text.str.strip() == '').sum(), len(text))}.", "",
        md_table(pd.DataFrame(ac_rows)), "",
        "Projects with the highest share: " + ", ".join(f"{k} {100 * v:.1f}%" for k, v in top.items()) + ".", "",
    ]

    # ---- 6. Dependencies and reopenings -----------------------------------------------------
    dep = links[links.Name.isin(DEPENDENCY_LINKS)]
    cand_dep = cand.ID.isin(dep.Issue_ID)
    reopened = status_log[status_log.To_String.fillna("").str.lower() == "reopened"].Issue_ID
    cand_reopened = cand.ID.isin(reopened)
    out += [
        "## 6. Dependencies and reopenings (candidates)", "",
        f"- Dependency link types used ({', '.join(sorted(DEPENDENCY_LINKS))}): {len(dep):,} link rows "
        "(each link is stored in both directions).",
        f"- Candidates with at least one dependency link: {cand_dep.sum():,} ({pct(cand_dep.sum(), len(cand))}).",
        f"- `Issue_Link` has no creation date. `Change_Log` has {len(link_changes):,} 'Link' changes, which is where "
        "the date a blocker appeared has to come from (R4, blocker_count at commitment).",
        f"- Candidates reopened at least once (R6 signal): {cand_reopened.sum():,} ({pct(cand_reopened.sum(), len(cand))}).", "",
    ]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=config.REPO_ROOT / "ml-engine" / "reports" / "tawos-profile.md")
    args = parser.parse_args(argv)
    report = build_report()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report, encoding="utf-8")
    print(report)
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
